<?php

namespace Partygames\TriviaGame;

use Illuminate\Support\ServiceProvider;
class TriviaGameServiceProvider extends ServiceProvider
{

    public function boot()
    {
        $this->loadRoutesFrom(__DIR__.'/routes/web.php');
        $this->loadViewsFrom(__DIR__.'/views', 'trivia');
        $this->loadMigrationsFrom(__DIR__.'/database/migrations');
        $this->publishes([
            __DIR__.'/views' => resource_path('views/vendor/trivia'),
        ]);
    }

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }

}