<?php

namespace PartyGames\TriviaGame;

use Illuminate\Support\ServiceProvider;
class TriviaGameServiceProvider extends ServiceProvider
{

    public function boot()
    {
        //$this->loadRoutesFrom(__DIR__.'/../routes/web.php');
        $this->loadViewsFrom(__DIR__.'/../resources/views', 'trivia-game');
        $this->loadMigrationsFrom(__DIR__.'/../database/migrations');
        $this->publishes([
            __DIR__.'/views' => resource_path('views/vendor/trivia'),
        ]);
    }

    public function register()
    {
        $this->mergeConfigFrom(
            __DIR__.'/../config/settings.php', 'settings');

        //parent::register(); // TODO: Change the autogenerated stub
    }

}